### PR TITLE
Buffer messages

### PR DESCRIPTION
**Pull request by SebastianOsuna**
Buffer a certain number of messages and send them to the clients upon connection.

### CODE REVIEW

**Comment by moccos** [comment]
It' s nice feature. Thanks for your patch (and fixing my typo ;) )

Before releasing the next version, I'll add buffering timeout feature.

**Comment by moccos** [comment]
Sorry. I misunderstood your PR at first.
This feature aims "limiting the number of messages" (to avoid sending a lot of messages). Is is right?
I'll change the parameter name.

**Comment by moccos** [comment]
Sorry again.
It is "Buffer several messages to send them to the new connection".
I'll use the original parameter name _buffered_messages_.
Thanks.

**Comment by SebastianOsuna** [comment]
😃

**Pull request merged**
